# Generated by Django 3.2.9 on 2021-11-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='call_num',
            new_name='phone_number',
        ),
    ]
