# Generated by Django 3.2.9 on 2021-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contacts',
            field=models.IntegerField(verbose_name=11),
        ),
    ]
